# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=gently
      - POSTGRES_PASSWORD=gently
      - POSTGRES_DB=gently
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5447:5432
